# ---------------------------------------------------------------------
# HOW TO BUILD THIS IMAGE
# @remarks
# Normally, we use Docker Compose to build everything including this,
# but here's how to build this separately just in case you need to.
#
# @example
# cd BeeMovr
# docker build -f ./Dockerfile.beemovr -t beemovr .
#
# HOW TO RUN THIS IMAGE
# @remarks
# Running the example below runs BeeMovr through Node.js at:
#   http://localhost
#
# @example
# docker run -p 80:3000 beemovr -v /app/database --name beemovr-database
#
# HOW TO DELETE THIS IMAGE
# @example
# docker image rm beemovr -f
# ---------------------------------------------------------------------
FROM ghcr.io/pnpm/pnpm:11

LABEL com.beemovr.description="https://github.com/soobinrho/BeeMovr"
LABEL com.beemovr.maintainer="Soobin Rho <soobin@nsustain.com>"

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN pnpm runtime set node 22 -g

WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile

CMD ["pnpm", "start"]
